--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-03-18 12:00:12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE weather_station;
--
-- TOC entry 3334 (class 1262 OID 16650)
-- Name: weather_station; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE weather_station WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Ukrainian_Ukraine.1251';


ALTER DATABASE weather_station OWNER TO postgres;

\connect weather_station

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16658)
-- Name: measurements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.measurements (
    id integer NOT NULL,
    temperature real NOT NULL,
    raining boolean NOT NULL,
    sensor_id integer,
    "time" timestamp without time zone NOT NULL
);


ALTER TABLE public.measurements OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16657)
-- Name: measurements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.measurements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16652)
-- Name: sensors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensors (
    id integer NOT NULL,
    name character varying(30) NOT NULL
);


ALTER TABLE public.sensors OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16651)
-- Name: sensors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sensors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3328 (class 0 OID 16658)
-- Dependencies: 217
-- Data for Name: measurements; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (1, 23.4, true, 1, '2023-03-17 13:28:30');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (2, 22.6, true, 1, '2023-03-17 13:47:59');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (3, 20.1, true, 1, '2023-03-16 14:22:05');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (4, 19.1, true, 1, '2023-03-17 23:51:05');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (5, 23.4, false, 1, '2023-03-17 15:00:43.31347');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (6, 18.4, false, 1, '2023-03-17 15:15:57.598439');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (11, 7, false, 3, '2023-03-17 14:00:30.394');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (8, -8, false, 3, '2023-03-17 05:52:07.973');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (9, -6, false, 3, '2023-03-17 07:52:19.66');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (12, 12, false, 3, '2023-03-17 16:00:36.476');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (10, -2, false, 3, '2023-03-17 10:59:25.25');
INSERT INTO public.measurements (id, temperature, raining, sensor_id, "time") VALUES (7, -8.56, false, 3, '2023-03-17 05:00:59.63');


--
-- TOC entry 3326 (class 0 OID 16652)
-- Dependencies: 215
-- Data for Name: sensors; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.sensors (id, name) VALUES (1, 'West-Kyiv');
INSERT INTO public.sensors (id, name) VALUES (2, 'East-Kyiv');
INSERT INTO public.sensors (id, name) VALUES (3, 'North-Kyiv');


--
-- TOC entry 3335 (class 0 OID 0)
-- Dependencies: 216
-- Name: measurements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.measurements_id_seq', 1018, true);


--
-- TOC entry 3336 (class 0 OID 0)
-- Dependencies: 214
-- Name: sensors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sensors_id_seq', 7, true);


--
-- TOC entry 3181 (class 2606 OID 16662)
-- Name: measurements measurements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurements_pkey PRIMARY KEY (id);


--
-- TOC entry 3179 (class 2606 OID 16656)
-- Name: sensors sensors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT sensors_pkey PRIMARY KEY (id);


--
-- TOC entry 3182 (class 2606 OID 16663)
-- Name: measurements measurements_sensor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurements_sensor_id_fkey FOREIGN KEY (sensor_id) REFERENCES public.sensors(id) ON DELETE SET NULL;


-- Completed on 2023-03-18 12:00:12

--
-- PostgreSQL database dump complete
--

